feat(support): storage api, closes #17
redbeestudios/hexagon pull request #21
Opened 2021-07-05 21:20 UTC by MarcoScabbiolo

2021-07-06 04:02 UTC, Lt-Mayonesa requested changes
Me copa hasta ahora, creo que esto está soportado pero decime que pensas:

Yo veo 3 tipos de configuraciones que querría guardar:
 - configuraciones de Hexagon en sí (ej: `~/.hexagon/config.yaml`)
 - configuraciones de la CLI (ej: `~/.hexagon/mi-custom-cli/config.yaml`)
 - configuraciones de las tools de una CLI (ej: `~/.hexagon/mi-custom-cli/mi-tool.yaml`)
 
Igual ahora que lo pienso quizas esto lo armaste como API para archivos y no para configuraciones, jeje, tu dime.

2021-07-06 13:20 UTC, MarcoScabbiolo commented on hexagon/support/storage.py
> +        "HEXAGON_STORAGE_PATH", os.path.expanduser("~/.hexagon")
es mas comun `~/.hexagon`. Para windows te lo guarda en /User/.../AppData/hexagon/...

2021-07-06 13:22 UTC, Lt-Mayonesa commented on hexagon/support/storage.py
> +        "HEXAGON_STORAGE_PATH", os.path.expanduser("~/.hexagon")
Común no siempre es bueno, jaja https://stackoverflow.com/a/1024216

2021-07-06 13:25 UTC, MarcoScabbiolo commented on hexagon/support/storage.py
> +def store_user_data(app: str, key: str, data: InputDataType, append=False):
Es un key-value, la flexibilidad esta en los values. Ahora soporta strings, lista de strings y objetos (diccionarios). El append lo puse por conveniencia y funciona para los tres tipos (para objetos hace un merge deep), es para evitar tener que leer antes de escribir para casos de uso comunes

2021-07-06 13:26 UTC, MarcoScabbiolo commented on hexagon/support/storage.py
> +                else lines
lo formatea asi black

2021-07-06 13:33 UTC, MarcoScabbiolo commented on hexagon/support/storage.py
> +    file_path = os.path.join(dir_path, file_name)
`_resolve_storage_path` se usa en el load tambien, la diferencia es que uno asume la extension por el dato y otro la lee directamente del archivo, se puede simplificar la funcion haciendo una auxiliar para esa parte, pero no se va a usar en otro lugar por lo que daria lo mismo

2021-07-06 14:44 UTC, MarcoScabbiolo commented on hexagon/__main__.py
> +            )
Ahi hice que tome la configurada por defecto

2021-07-06 17:17 UTC, Lt-Mayonesa commented on hexagon/support/storage.py
> +def store_user_data(app: str, key: str, data: InputDataType, append=False):
claro, entiendo la conveniencia pero se me hace que complejiza un poco el uso del storage. Yo preferiría que internamente storage resuelva solo si tiene que leer antes o no. Quizas charlemos un poco después los casos de uso que tenías en la cabeza

2021-07-06 17:44 UTC, MarcoScabbiolo commented on hexagon/support/storage.py
> +def store_user_data(app: str, key: str, data: InputDataType, append=False):
Es que no tiene forma de saber si queres sumar a lo que ya tenes o pisar todo, eso lo tiene que definir el usuario.
Si estas guardando texto en muchas lineas usarias append is queres agregar algo conservando lo que ya tenias.
Si estas guardando un objeto con unas configuraicones y queres actualizar solo unas propiedades manteniendo lo que tenias antes usas append para modificar parcialmente solo una cosa.

2021-07-06 20:02 UTC, Lt-Mayonesa commented on hexagon/support/storage.py
> +def store_user_data(app: str, key: str, data: InputDataType, append=False):
De una, creo que a lo que iba es que yo esperaría que esta API me quite complejidad (ej: append o write de archivos) y no que la mantenga. Pero quizas me estoy haciendo la cabeza al dope, avancemos así por ahora

2021-07-06 20:11 UTC, Lt-Mayonesa approved these changes

2021-07-06 20:14 UTC, Lt-Mayonesa approved these changes

2021-07-06 20:14 UTC, Lt-Mayonesa commented on hexagon/support/storage.py
> +    return (os.path.join(base_dir, app, *key_splitted[:-1]), *key_splitted[-1:])
acá los paréntesis son redundantes :)

2021-07-06 20:14 UTC, Lt-Mayonesa commented on hexagon/support/storage.py
> +    return (file_path, value_type)
acá también :)

2021-07-06 20:14 UTC, Lt-Mayonesa commented on hexagon/support/storage.py
> +    "merges b into a"
este docstring debería tener 3 comillas
```suggestion
    """
    merges b into a
    """
```

2021-07-07 13:27 UTC, MarcoScabbiolo commented on hexagon/support/storage.py
> +    return (os.path.join(base_dir, app, *key_splitted[:-1]), *key_splitted[-1:])
mira vos, me gusta lo cuidada que esta la legibilidad en python

2021-07-07 13:43 UTC, MarcoScabbiolo commented on hexagon/support/storage.py
> +    return (os.path.join(base_dir, app, *key_splitted[:-1]), *key_splitted[-1:])
en python 3.7 no funciona para esta linea en particular, supongo que por el `*`

2021-07-07 13:43 UTC, merged